### PR TITLE
New tuto on masternode creation

### PR DESCRIPTION
**Pull request by grnt4v**
Removed the useless apt stuff, create an ips user so that we won't run ipsd as root, automates the process of retrieving the nodes...

### CODE REVIEW

**Comment by EmbeddedAndroid** [comment]
Thanks for these, but the content is duplicated much in the other guides. Is there a chance you can consolidate this information in the other guides?

**Review by EmbeddedAndroid — CHANGES_REQUESTED** [review]
This is duplicated content from our other guides, can you consolidate this info?

**Comment by grnt4v** [comment]
Yes I will.

**Comment by grnt4v** [comment]
Consolidated as #7

**Pull request closed without merging**
